const facts=[
 {category:'Космос',title:'На Венере день длится дольше года',text:'Венера вращается вокруг своей оси так медленно, что один её день занимает 243 земных дня. А полный оборот вокруг Солнца она совершает за 225 дней.',source:'NASA',icon:'◒'},
 {category:'Природа',title:'У деревьев есть свой интернет',text:'Грибы соединяют корни деревьев под землёй в огромную сеть. Через неё растения могут обмениваться питательными веществами и предупреждать друг друга об опасности.',source:'Nature Journal',icon:'✣'},
 {category:'История',title:'Викинги носили украшения из льда',text:'Археологи нашли на севере Скандинавии украшения, вырезанные из прозрачного льда. В холодном климате они могли сохраняться достаточно долго, чтобы быть частью ритуалов.',source:'Archaeology Magazine',icon:'✦'},
 {category:'Наука',title:'У осьминога три сердца',text:'Два сердца осьминога прокачивают кровь через жабры, а третье отправляет её по всему телу. Когда осьминог плывёт, главное сердце перестаёт биться.',source:'Smithsonian',icon:'♡'},
 {category:'Технологии',title:'Первый компьютерный баг был настоящим',text:'В 1947 году инженеры нашли мотылька, застрявшего между контактами компьютера Mark II. Они приклеили его в журнал с подписью «первый реальный bug».',source:'Harvard Archives',icon:'▦'},
 {category:'Психология',title:'Запахи сильнее всего будят воспоминания',text:'Обонятельные сигналы почти напрямую связаны с областями мозга, отвечающими за память и эмоции. Поэтому запах старого дома может мгновенно вернуть вас в детство.',source:'Cognitive Science',icon:'☼'}
];
const categories=[['◒','Космос','12 фактов'],['✣','Природа','18 фактов'],['◉','История','24 факта'],['⌁','Наука','31 факт'],['▦','Технологии','16 фактов'],['☼','Психология','14 фактов']];
let current=0,score=0,saved=0;
const $=s=>document.querySelector(s);
function renderCategories(){ $('#category-grid').innerHTML=categories.map((c,i)=>`<div class="category" data-index="${i}"><span class="category-icon">${c[0]}</span><span>${c[1]}</span><small>${c[2]}</small></div>`).join(''); document.querySelectorAll('.category').forEach(el=>el.onclick=()=>{current=Number(el.dataset.index);renderFact();showToast('Показываем факты о '+categories[current][1]);}); }
function renderFact(){const f=facts[current%facts.length];$('#fact-category').textContent=f.category;$('#fact-number').textContent='#'+String(current+1).padStart(3,'0');$('#fact-title').textContent=f.title;$('#fact-text').textContent=f.text;$('#fact-source').textContent='Источник: '+f.source;$('#fact-illustration .planet').textContent=f.icon;$('#meter-fill').style.width=Math.max(8,Math.min(100,8+score*12))+'%';$('#interest-status').textContent=score===0?'Начинаем знакомство':score<3?'Уже кое-что понимаем':'Лента настроена под вас';}
function react(isYes){score++; current=(current+1)%facts.length; const card=$('#fact-card');card.classList.remove('dragging');card.style.transition='transform .35s cubic-bezier(.2,.8,.2,1), opacity .35s';card.style.transform=`translateX(${isYes?110:-110}px) rotate(${isYes?7:-7}deg)`;card.style.opacity='0';setTimeout(()=>{renderFact();card.style.transition='';card.style.transform='';card.style.opacity='1';},350);showToast(isYes?'Запомнили — добавим похожие':'Поняли — будем показывать меньше такого');}
function showToast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>t.classList.remove('show'),2200)}
$('#yes-button').onclick=()=>react(true);$('#no-button').onclick=()=>react(false);$('#save-button').onclick=()=>{saved++;$('.saved-count').textContent=saved;$('#save-button').querySelector('span').textContent='♥';showToast('Факт сохранён')};$('#share-button').onclick=()=>{navigator.clipboard?.writeText($('#fact-title').textContent);showToast('Ссылка скопирована')};
$('#theme-toggle').onclick=()=>{document.body.classList.toggle('dark');const dark=document.body.classList.contains('dark');$('#theme-toggle').textContent=dark?'☀':'☾';localStorage.setItem('factday-theme',dark?'dark':'light');};
if(localStorage.getItem('factday-theme')==='dark'){document.body.classList.add('dark');$('#theme-toggle').textContent='☀';}
let startX=0,dragging=false;const card=$('#fact-card');card.addEventListener('pointerdown',e=>{if(e.target.closest('button'))return;startX=e.clientX;dragging=true;card.classList.add('dragging');card.setPointerCapture(e.pointerId)});card.addEventListener('pointermove',e=>{if(!dragging)return;const diff=e.clientX-startX;card.style.transform=`translateX(${diff}px) rotate(${diff/24}deg)`;card.style.opacity=String(1-Math.min(Math.abs(diff)/600,.35));});card.addEventListener('pointerup',e=>{if(!dragging)return;dragging=false;const diff=e.clientX-startX;card.classList.remove('dragging');if(Math.abs(diff)>75)react(diff>0);else{card.style.transform='';card.style.opacity='1';}});card.addEventListener('pointercancel',()=>{dragging=false;card.classList.remove('dragging');card.style.transform='';card.style.opacity='1';});renderCategories();renderFact();
